# Generated by Django 4.1.6 on 2023-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_replied", models.BooleanField(default=False)),
            ],
        ),
    ]
