# Generated by Django 4.1.6 on 2023-02-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("profile_picture", models.ImageField(upload_to="picture/")),
            ],
        ),
    ]
