# Generated by Django 4.1.6 on 2023-02-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky", "0004_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                ("field_of_study", models.CharField(max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
