# Generated by Django 4.1.6 on 2023-02-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky", "0005_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
