# Generated by Django 4.1.6 on 2023-02-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky", "0006_currentjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentjob", name="end_date", field=models.DateField(),
        ),
    ]
