# Generated by Django 4.1.6 on 2023-02-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky", "0007_alter_currentjob_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentjob",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
